name: Kevin Ross Thompson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.694629130885005
  saturation: 0.5
  rhythmicContrast: 0.9826207677833736
purpose: []
